version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      - mysql-django
  
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: django_sql_dev
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - /volume1/docker/django-sql-dev/app:/app
    ports:
      - "9898:8000"
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
    networks:
      - mysql-django
volumes:
  data:

networks:
  mysql-django: